global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'transit-ingestion'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ingestion-api:8000']

  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']