global:
  scrape_interval: 5s # Faster for demo purposes
  evaluation_interval: 15s

scrape_configs:
  # --- This connects our FastAPI ---
  - job_name: 'transitflow-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['serving-api:8001']

  # OPTIONAL: If Ingestion is also in docker, use 'producer:8000'
  # If it's running on Mac via 'make run', keep host.docker.internal
  - job_name: 'transit-ingestion'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['producer:8000']
        
  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:8081']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']